coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 30%
        threshold: 1%

    patch:
      default:
        target: 0%
        threshold: 0%

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true

codecov:
  require_ci_to_pass: yes